### PR TITLE
support react native >=0.59

### PR DESCRIPTION
**Pull request by staltz**

### CODE REVIEW

**Comment by staltz** [comment]
Thanks for the fast merge! Could you publish version `1.2.0`?

**Comment by Happy0** [comment]
@staltz - sure. I just realised I'll have to wait until I'm home later to do that, because I don't have my 2fa device on me at the moment - woops!

**Comment by staltz** [comment]
No hurry whatsoever :sunglasses: :sun_behind_small_cloud:

**Comment by Happy0** [comment]
@staltz - that's it published at `1.2.0` :)

**Pull request merged**
